<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style type="text/css">
    </style>
</head>
<body>
<h1>Welcome to the Linked Data Infrastructure</h1>
<?php
foreach ($this->_menuFiles as $menuFile) {
    include $menuFile;
}

foreach ($this->_contentFiles as $contentFile) {
    include $contentFile;
}
?>
<?php if (!empty($this->_debugLog)) : ?>

<div class="debug" id="debugConsole">
<h3>Debuglog:</h3>
<pre>
<?= $this->_debugLog ?>
</pre>
</div>

<?php endif; ?>

This is a project of the Research Group <a href="http://aksw.org">Agile Knowledge Engineering and Semantic Web (AKSW)</a>

<a href="https://github.com/AKSW/LinkedDataInfrastructure">
<img style="position: absolute; top: 0; right: 0; border: 0;" src="<?= $this->baseUri ?>resources/forkme_github.png" alt="Fork me on GitHub">
</a>

</body>
</html>
