<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style type="text/css">
    </style>
</head>
<body>
<h1>Welcome to the Semantic Pinback Hub</h1>
<?php
foreach ($this->_menuFiles as $menuFile) {
    include $menuFile;
}

foreach ($this->_contentFiles as $contentFile) {
    include $contentFile;
}
?>
<?php if (!empty($this->_debugLog)) : ?>

<div class="debug" id="debugConsole">
<h3>Debuglog:</h3>
<pre>
<?= $this->_debugLog ?>
</pre>
</div>

<?php endif; ?>
</body>
</html>
