<ul class="menu">
<li><a href="?c=index&amp;a=index">overview</a></li>
<li><a href="?c=pingback&amp;a=ping">send pingback</a> (PinbackController, pingAction)</li>
<li><a href="?c=feed&amp;a=getfeed">get feed</a> (FeedController, getFeed)</li>
<li><a href="?c=push&amp;a=publishfeed">trigger publish</a> (PushController, publish)</li>
<li><a href="?c=model&amp;a=export">export the whole model</a> (ModelController, export)</li>
<li><a href="?c=model&amp;a=query">query the model</a> (ModelController, query)</li>
<li><a href="?c=model&amp;a=diff">diff of a resource</a> (ModelController, diff)</li>
</ul>
