<form method="post">
<legend>This method sends a pingback to this pingback service</legend>
<input type="hidden" name="c" value="pingback" />
<input type="hidden" name="a" value="ping" />
<label for="source">source</label>
<input type="text" name="source" id="source" /><br />
<label for="target">target</label>
<input type="text" name="target" id="target" /><br />
<label for="comment">comment</label>
<textarea name="comment" id="comment">
</textarea><br />
<input type="submit" />
</form>
